### ISSUE TITLE
TestUtils

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/GPLikelihoods.jl#18]
I think before implementing any more likelihoods we should think carefully about what standardised tests we want to run on them, similarly to what I've just done in this PR: https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/159

Looking at the various open PRs (#17, #16 , #15, and maybe #14), and the already implemented likelihoods (`Gaussian` and `Poisson`) there appears to be quite a lot of repeated code in the tests. It would be great to get a handle on this before it becomes too large a job to easily refactor.

Pulling out some common themes from these, it looks like we want to be testing that

1. the API is satisfied
2. the length is correct
3. functor works properly

@sharanry you've done most of the work on this so far. Is there anything else that's obvious to you that we're missing?

There's also quite a lot of code that manually generates input and output data / constructs appropriate "latent" `AbstractGPs` at the minute -- in my opinion it would be a very good idea to factor this code out as well.

**Comment by sharanry** [comment]
Totally agree! I also think the 3 things you mentioned are the main points to cover.

We could also start testing different AD like in kernel functions. I think this needs to be done in AbstractGPs too.

**Comment by willtebbutt** [comment]
Yeah, we really need to figure out the correct way to test AD in general. Currently everyone writes their own code to test a given AD, which is just bad -- the ADs should provide utility to do this.

For now we're probably stuck with code duplication though.

**Comment by theogf** [comment]
Sounds like this is solved to me no?
