### ISSUE TITLE
Package registration, name, interaction with rest of ecosystem

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/GPLikelihoods.jl#33]
"GPLikelihoods.jl" is currently not a registered package. This makes it more difficult than necessary for users of this package such as https://github.com/rossviljoen/SparseGPs.jl. It is overdue to register the code inside this repo.

* There are concerns about too many small packages - we could move this code into a separate package - what package would that be?
* This package currently has no dependency in either direction with AbstractGPs.jl - it is used by SparseGPs.jl, but _could_ also be used e.g. by GLM implementations (such as https://github.com/JuliaStats/GLM.jl) - can we combine forces, and perhaps rename to "just" LikelihoodFunctions.jl (as proposed in https://github.com/JuliaGaussianProcesses/GPLikelihoods.jl/issues/4)?
  **Update:** GLM.jl defines link functions in https://github.com/JuliaStats/GLM.jl/blob/master/src/glmtools.jl

**Comment by theogf** [comment]
I think that if we name it LikelihoodFunctions.jl, it should not lie in the JuliaGaussianProcesses organisation. But in JuliaStats or something, that would make harder for us to contribute...

**Comment by willtebbutt** [comment]
Hmm yeah, that does look helpful. They've probably got more dependencies than would be ideal for us, but possibly we could try and sort that out?

It's not obvious to me that their "likelihoods" are quite what we're after.

Regarding naming the package, what about something like "ConditionalDistributions.jl", in recognition of the fact that we are, indeed, defining a load of conditional distributions and functions on them? I don't feel too strongly about the name though.

**Comment by willtebbutt** [comment]
@st-- @theogf one and a bit weeks on, what are your thoughts on this problem?

My feeling is that the links look quite nice, and probably we want to try and use them, but that we probably still need our likelihoods. My inclination is therefore to go ahead and register this package.

What are your thoughts @st-- @theogf ?

**Comment by rossviljoen** [comment]
It's getting a bit awkward to develop SparseGPs without this being registered, so I'd definitely be in favour of registering it

**Comment by willtebbutt** [comment]
That's my inclination -- we should just register it as-is with the current name and everything, and deprecate it later if that becomes necessary for some reason.

**Comment by willtebbutt** [comment]
Registration PR open: https://github.com/JuliaRegistries/General/pull/40456

If anyone continues to have a strong objection to this, we can cancel it again, but my preference would be for this to get registered and for us to crack on with development.

**Comment by st--** [comment]
Did we not agree to rename it to likelihood functions?

On Tuesday, August 3, 2021, willtebbutt ***@***.***> wrote:
> Registration PR open: JuliaRegistries/General#40456
>
> If anyone continues to have a strong objection to this, we can cancel it
again, but my preference would be for this to get registered and for us to
crack on with development.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.<
https://ci4.googleusercontent.com/proxy/cFiPKdlQn272uF9ezCqGeq4-R2Q_18apbTY3eD2LjCuP5btcz4ndCEEVd4Ww5nm4gYeloTa9Doxw9NMACV3WqcB4PXrfEeVtb-v-DV79O2IBGQFBX7oCsMQVa-QWnx06v86fedlLKfDqjize3fpC60uh3asd0R15YjG9UjejThxyP1QGaRABjfUAJ04traJX2j8KCbPG9_xZFr1eYq1pXrQBDDgr2dCO8vg7Deyw7Q=s0-d-e1-ft#https://github.com/notifications/beacon/ABL7FDYDHQSQWS3QFS3NHQDT27B6LA5CNFSM5A2BMALKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGUTOAFQ.gif>

**Comment by willtebbutt** [comment]
> Did we not agree to rename it to likelihood functions?

Ah, sorry, I think I understood the discussion differently from you. I thought we were going to rename LikelihoodFunctions if we joined forced with others.

Either way, we can always swap out rebrand to LikelihoodFunctions at a later date if we do generalise.

**Comment by theogf** [comment]
@st-- @willtebbutt I think this issue can now be closed?

**Comment by willtebbutt** [comment]
Yup, I'm happy to close.
