### ISSUE TITLE
Move expected_loglik here & additional design discussion

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/GPLikelihoods.jl#42]
Complement to https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/issues/53

The expectation of the log-likelihood under q(f), ∫ q(f) log p(y | f) df, isn't specific to ApproximateGPs themselves, and if someone added a new likelihood here, it'd be great if they had visibility into also providing e.g. analytic implementation of expected_loglik or at least thinking about what _default_quadrature should be.

`expected_loglik` currently has the following signature:
```julia
expected_loglik(quadrature::QuadratureMethod, y::AbstractVector, q_f::AbstractVector{<:Normal}, lik)
```

Some questions on the design:

1. To me it would seem more natural to either order it as
`expected_loglik(quadrature, q_f, lik, y)` or `expected_loglik(quadrature, lik, q_f, y)` -- we're unlikely to dispatch on `y` (it's implicitly defined by what the likelihood is already), and the first form matches the common maths notation much more closely.

2. `expected_loglik` takes a Vector `y`, a Vector `q_f`, and a `lik` function that maps from scalar `f` to UnivariateDistribution; `expected_loglik` then does the broadcasting internally. Is that what we want?

  - Would it be better (cleaner) to have `expected_loglik` handle scalars only (but this might result in some performance loss for e.g. recomputing the Gauss-Hermite points and weights for each data point)?
  - Should we expect `lik` to take the full Vector `fs` and return e.g. a Product() of UnivariateDistributions (though this might make the expectation code more complicated)?
  - How would we want to handle the heteroskedastic case, where we do want to include the correlations across the two outputs at each data point, but independence between different data points (not sure how we would handle that on the AbstractGPs side given that multi-output is all "output as input")?

3. If we want to support e.g. Expectation Propagation as well, we should also provide ∫ q(f) p(y | f) df: the quadrature fallbacks are going to be exactly the same, just evaluating `pdf` instead of `loglikelihood` (NB- should that be `logpdf`? the difference is in summing over ys...). Should we have `expected_pdf` separately (maybe re-using internal quadrature methods)?

**Comment by devmotion** [comment]
> To me it would seem more natural to either order

Could we make `lik` the first argument such that one can use Julia's `do` syntax (see https://docs.julialang.org/en/v1/manual/style-guide/#Write-functions-with-argument-ordering-similar-to-Julia-Base)?

And maybe one could use the name `expected_loglikelihood` or `mean_loglikelihood` to be more consistent with `StatsBase.loglikelihood`?

**Comment by theogf** [comment]
> Could we make lik the first argument such that one can use Julia's do syntax (see https://docs.julialang.org/en/v1/manual/style-guide/#Write-functions-with-argument-ordering-similar-to-Julia-Base)?
> And maybe one could use the name expected_loglikelihood or mean_loglikelihood to be more consistent with StatsBase.loglikelihood?

I really like both ideas and have a preference for `expected_loglikelihood`.

> How would we want to handle the heteroskedastic case

I think it's fair to provide specialized methods for the 2D and maybe 3D cases (by D I mean the dimension of the GP input to the likelihood), because quadrature would not scale higher.

**Comment by st--** [comment]
> And maybe one could use the name expected_loglikelihood or mean_loglikelihood to be more consistent with StatsBase.loglikelihood?

If that's what we mean, I'd agree (not `mean_loglikelihood` though, that's making the dependence on q(f) too subtle IMO), but I'm wondering if that's the case or what we actually mean here is `expected_logpdf`?

**Comment by st--** [comment]
> I think it's fair to provide specialized methods for the 2D and maybe 3D cases (by D I mean the dimension of the GP input to the likelihood), because quadrature would not scale higher.

From an implementation point of view, yes, that's why we used Monte Carlo for the expectation with softmax likelihood for multi-class classification. But it would be good if neither SVGP in ApproximateGPs nor the end user would have to call different methods depending on their type of likelihood.

**Comment by st--** [comment]
> Could we make lik the first argument such that one can use Julia's do syntax (see https://docs.julialang.org/en/v1/manual/style-guide/#Write-functions-with-argument-ordering-similar-to-Julia-Base)?

I don't think `expected_loglikelihood` (or whatever we end up calling it) would be called a lot directly by the user/ from the REPL, so I don't think there's much value in it. The `lik` likelihood object is specified very indirectly through the `LatentGP` constructor.

**Comment by theogf** [comment]
> what we actually mean here is expected_logpdf?

I don't think it's what we mean since sometimes likelihoods are not pdfs...

> would have to call different methods depending on their type of likelihood.

We can easily dispatch one unique method and have underlying `_expected_loglikelihood_2d` etc...

> The lik likelihood object is specified very indirectly through the LatentGP constructor.

I actually like the idea of the `do` syntax, especially if one uses custom weird likelihood. It's similar to the problem you mention in #43 where you don't want tobuild a link explicitely

**Comment by st--** [comment]
> I don't think it's what we mean since sometimes likelihoods are not pdfs...

Ah, that might be an issue of terminology overloading. "Likelihood" can mean the _object_ `p(y | f)` (which we can represent as `(f, y) -> pdf(dist_y_given_f(f), y)`), or the _value_ of `p(y | f)` for a certain value f (for fixed y) - which generalises to the 1d function `f -> pdf(dist_y_given_f(f), y)`. But in terms of code, I think it makes most sense to think of the likelihood as `dist_y_given_f` as a function from a value f to a Distribution.

Distributions defines `logpdf` and `loglikelihood` roughly as follows:
```julia
logpdf(univariate_distribution, ys::Vector) = map(y -> logpdf(univariate_distribution, y), ys)
loglikelihood(univariate_distribution, ys) = sum(logpdf(univariate_distribution, ys))
```

We could maybe think of the generalisation to VI and EP as
`expected_(logpdf, qf, ys, quadrature)` and `expected_(pdf, qf, ys, quadrature)`...
