### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/GPLikelihoods.jl#5]
I have the feeling that LikelihoodFunctions is a bit too general for this package. If I understand correctly, this package aims at propose models with Gaussian and non-Gaussian likelihoods. Shouldn't the name be then `GPLikelihoods`, `NonConjugateGPs` or something like this?

**Comment by yebai** [comment]
`NonConjugateGPs` sounds sensible: it reflects well what the package provides, and is self-descriptive I think.
