### ISSUE TITLE
Use InverseFunctions

### ISSUE THREAD

**Issue by devmotion** [JuliaGaussianProcesses/GPLikelihoods.jl#52]
The package InverseFunctions.jl will be available in the registry soon and contain `inverse` + definitions for functions in base. If other packages such as LogExpFunctions implement this interface we could replace `GPLikelihoods.inverse` with `InverseFunctions.inverse` and remove our definitions.

**Comment by devmotion** [comment]
Note: We can't switch before LogExpFunctions and StatsFuns support it though (if we don't want to introduce type piracy).

**Comment by oschulz** [comment]
Do we already have something pending on StatsFuns?

**Comment by devmotion** [comment]
No, I didn't push this issue the last weeks. I am up for reviewing a PR though.

**Comment by oschulz** [comment]
> I am up for reviewing a PR though.

Sure, I can do one. Which functions in StatsFuns should be targeted?

**Comment by oschulz** [comment]
I guess the relevant functions in StatsFuns are the `cdf`, `ccdf`, `logcdf` and `logccdf` and their inverses, right (since the log/exp functions live in LogExpFunctions now)?

**Comment by devmotion** [comment]
Yes, I guess everything that's defined in StatsFuns and not in LogExpFunctions.

**Comment by oschulz** [comment]
Uh, I was just about to get started, and then realized that those function do of course all take multiple arguments - `InverseFunctions.inverse` doesn't support that (would be tricky to define what inverse means). We could define `InverseFunctions.inverse` (and even `ChangesOfVariables.with_logabsdet_jacobian` if we want) for `Base.Fix1(Distributions.cdf)` and so on in a generic fashion, though.

What does GPLikelihoods need, here?

**Comment by oschulz** [comment]
And I just saw sqrt/square in inverse.jl here. I actually had that in an eary draft of InverseFunctions, but then took it out because Base has no inverse of `sqrt` and hadn't seen sqrt/square used in variable trafos.

We should add `square` to InverseFunctions, though, if it's useful here.

**Comment by devmotion** [comment]
Ah true, yes, it only makes sense for one-argument functions. We only need `normcdf` and `norminvcdf` here.

**Comment by oschulz** [comment]
What about `sqrt`? Is it used, or just in inverse.jl for completeness?

**Comment by devmotion** [comment]
No, everything in `inverse.jl` is used. It is needed for the `SquareLink` (alias and constructor might be removed at some point but we still want to support it).

**Comment by oschulz** [comment]
Ok, then let's just add `square` to InverseFunctions. Should it be exported, you think?

Also - should we support it in ChangesOfVariables? Would require it to depend on InverseFunctions, but I don't think that should be a problem.

**Comment by oschulz** [comment]
InverseFunctions support `sqrt` now (JuliaRegistries/General#48374).
