### ISSUE TITLE
Question on implementation and type stability

### ISSUE THREAD

**Issue by simsurace** [JuliaGaussianProcesses/GPLikelihoods.jl#77]
I was studying the implementation of the expected likelihood and stumbled upon this:

https://github.com/JuliaGaussianProcesses/GPLikelihoods.jl/blob/498af318aecb891c1497e1a4a19c26dc7ebd0c47/src/expectations.jl#L84-L96

This uses `Broadcast.broadcasted`, which is not documented. If I'm not mistaken, this means that it is not part of Julia's public API, and could break at any point in time. Besides that, I wonder what is the advantage over this:

```julia
function expected_loglikelihood(
    gh::GaussHermiteExpectation, lik, q_f::AbstractVector{<:Normal}, y::AbstractVector
)
    # Compute the expectation via Gauss-Hermite quadrature
    # using a reparameterisation by change of variable
    # (see e.g. en.wikipedia.org/wiki/Gauss%E2%80%93Hermite_quadrature)
    return sum(expected_loglikelihood(gh, lik, q_fᵢ, yᵢ) for (q_fᵢ, yᵢ) in zip(q_f, y))
end
```
This also seems to be type-stable, while the current implementation isn't.

**Comment by devmotion** [comment]
While it's not documented, it's used in many core packages (eg StatsBase, Distributions, ...), so breaking it would break other parts of the pipeline already. The main advantage of `broadcasted` (if you use `instantiate`!) is that the `sum` will use pairwise summation. That's not the case if you use `zip` or other iterators.

**Comment by devmotion** [comment]
The main point is pairwise summation - while still being fast. `zip` does not use pairwise summation.

**Comment by devmotion** [comment]
An example that illustrates my point:
```julia
julia> using BenchmarkTools, LinearAlgebra

julia> A = vcat(1f0, fill(1f-8, 10^8));

julia> w = ones(Float32, length(A));

julia> f_dot(A, w) = dot(A, w)
f_dot (generic function with 1 method)

julia> f_sum_zip(A, w) = sum(Ai * wi for (Ai, wi) in zip(A, w))
f_sum_zip (generic function with 1 method)

julia> f_sum_broadcasted(A, w) = sum(Broadcast.instantiate(Broadcast.broadcasted(*, A, w)))
f_sum_broadcasted (generic function with 1 method)

julia> f_sum_mapfoldl(A, w) = mapfoldl(+, zip(A, w)) do (Ai, wi)
           Ai * wi
       end
f_sum_mapfoldl (generic function with 1 method)

julia> f_sum_mapreduce(A, w) = mapreduce(+, zip(A, w)) do (Ai, wi)
           Ai * wi
       end
f_sum_mapreduce (generic function with 1 method)

julia> f_dot(A, w)
1.9625133f0

julia> f_sum_zip(A, w)
1.0f0

julia> f_sum_broadcasted(A, w)
1.9999989f0

julia> f_sum_mapfoldl(A, w)
1.0f0

julia> f_sum_mapreduce(A, w)
1.0f0

julia> @btime f_dot($A, $w);
  42.887 ms (0 allocations: 0 bytes)

julia> @btime f_sum_zip($A, $w);
  140.985 ms (0 allocations: 0 bytes)

julia> @btime f_sum_broadcasted($A, $w);
  46.262 ms (0 allocations: 0 bytes)

julia> @btime f_sum_mapfoldl($A, $w);
  141.182 ms (0 allocations: 0 bytes)

julia> @btime f_sum_mapreduce($A, $w);
  141.659 ms (0 allocations: 0 bytes)
```

**Comment by simsurace** [comment]
Very nice, thanks. Strangely, `sum(A)` seems to give the result of the broadcasted sum above. Apparently it uses pairwise summation as well. I wonder why it doesn't when iterating over a `zip`. Would it make sense to have a pairwise iterator in `Base`? This seems like such a common pattern.

**Comment by devmotion** [comment]
Yes, `sum` on arrays uses also pairwise summation. `mapreduce` is specialized and uses pairwise operations for `AbstractArray` and `Broadcasted` (https://github.com/JuliaLang/julia/blob/bf534986350a991e4a1b29126de0342ffd76205e/base/reduce.jl#L235-L257), and `sum` is just `mapreduce(op, add_sum, ...)` under the hood.

**Comment by simsurace** [comment]
I see. It seems that something that zips multiple vectors but still allows linear indexing would accomplish the same thing as `Broadcast.broadcasted`. It's trivial to modify the linked `mapreduce_impl` to support two input arrays, but `mapreduce(*, +, A, w)` instead calls a different method which uses `Base.Generator` and seems to allocate. It seems that if pairwise summation is generally preferable and is the default for `sum(::AbstractArray)`, it should be for other reductions with `+` as well.

**Comment by simsurace** [comment]
I can't figure out the reason for `expected_loglikelihood` being type-unstable though. That does not happen in other examples as `f_sum_broadcasted` above.
